name: Show Context

on: 
    workflow_dispatch:
    push:

jobs:
    show:
        runs-on: ubuntu-latest
        steps:
        - name: Dump Github Context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo $GITHUB_CONTEXT

        - name: Test Github Property
          run: echo ${{ github.repository }}
