# 1
name: My first workflow # Name of the job

on: push # Action to execute this job

jobs:
    first_job:
        runs-on: ubuntu-latest # Machine where the workflow runs
        steps:

        - name: Welcome message # Name of the step
          run: | # Commands
              echo "My first Github Actions Job"
              ls .
              cat ../README.md
        - name: generate ascii art # Another Step name
          run: cowsay "MOOOOH" # Last command
