name: Matrix Workflow # Probaremos la Estrategia Matrix y al final tambien uso github actions var context

on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy: #Strategy funciona para definir entre 3 tipos matrix, fail-fast
            fail-fast: false # Esto si esta en true lo que hace es que si falla cualquier cosa detiene todo el workflow
            max-parallel: 2 # Los Jobs simultaneos que pueden correr
            matrix: 
                os: [ubuntu-latest, windows-latest]
                images: [hello-world, alpine]
                exclude:
                  - images: alpine
                    os: windows-latest
#                include:
 #                 - images: amd64/alpine
  #                  os: ubuntu-20.04
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo Docker Details
          run: docker info
          
        - name: Run Image on ${{ matrix.os }}
          run: docker run ${{ matrix.images }}

        - name: Running Context Variables
          run: |               
              echo "RUNNER=${{ runner.os }}"
              echo "JOB_ID=${{ job.check_run_id }}"

          
