#5
name: Workflow Demo

on:
  push

env: # Definir Variables de entorno
  ACCESS_ID: ${{ vars.ACCESS_ID }}
  ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }} # Este esta definido en el repositorio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID and ACCESS_SECRET
      run: echo -e "var $ACCESS_ID \nsecret $ACCESS_SECRET"
